# Your Discord bot token (Found at https://discord.com/developers/applications)
botToken: ""

# Your Discord bot client ID
clientId: ""

# Your Genius API client access token (Found at https://genius.com/developers)
geniusApiKey: ""

# The colour to use for embeds sent by the bot
embedColour: "#2B2D31"

# Whether analytics should be sent when starting the bot
# See https://github.com/NerdyTechy/Melody/wiki/Analytics
enableAnalytics: true

# Whether the bot should autocomplete search results
# Disable this if you're experiencing Unknown Interaction errors
enableAutocomplete: true

# Settings to control the bot's player and controller
player:
    # Leave VC when a song ends
    leaveOnEndDelay: "5m"
    # Leave VC when a song is stopped
    leaveOnStopDelay: "5m"
    # Leave VC when the channel is empty
    leaveOnEmptyDelay: "5m"
    # Deafen bot while playing
    # Off by default because it looks cleaner - the bot wont ever listen
    # to you, but the option is here just in case you want to be sure.
    deafenBot: false
    # Default volume when joining a VC
    defaultVolume: 100

# The emojis to be used in buttons for certain embeds
# See https://github.com/NerdyTechy/Melody/wiki/Using-Custom-Emojis
emojis:
    stop: "⏹"
    skip: "⏭"
    queue: "📜"
    pause: "⏯"
    lyrics: "📜"
    back: "⏮"

# Make Melody use a proxy when making requests.
# Useful if you're experiencing 429 errors.
# See https://github.com/NerdyTechy/Melody/wiki/Proxying-Requests
# Omit user:pass@ if your proxy does not require authentication.
proxy:
    enable: false
    connectionUrl: "http://username:password@123.45.67.89:1234"

# Make Melody use a custom YouTube cookie when making requests.
# This can help to prevent against receiving 429 rate limits from YouTube.
# See https://github.com/NerdyTechy/Melody/wiki/YouTube-Cookies
cookies:
    useCustomCookie: false
    youtubeCookie: ""

# Make Melody emit advanced debug logs
# Unless you've specifically been asked by a developer to enable this,
# you should just leave this disabled to prevent logs from being spammed.
debug: false
