blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/NerdyTechy/Melody/discussions
    about: If you're having trouble setting up Melody, feel free to create a discussion.
